declare module 'gl-matrix' {
  export const glMatrix: any;
  export const mat2: any;
  export const mat2d: any;
  export const mat3: any;
  export const mat4: any;
  export const quat: any;
  export const quat2: any;
  export const vec2: any;
  export const vec3: any;
  export const vec4: any;
  export const ReadonlyMat2: any;
  export const ReadonlyMat2d: any;
  export const ReadonlyMat3: any;
  export const ReadonlyMat4: any;
  export const ReadonlyQuat: any;
  export const ReadonlyQuat2: any;
  export const ReadonlyVec2: any;
  export const ReadonlyVec3: any;
  export const ReadonlyVec4: any;
}
