// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wogenchxhjipmhfojker.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvZ2VuY2h4aGppcG1oZm9qa2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzE4NjcsImV4cCI6MjA2NzA0Nzg2N30.sAqsfjAnYFK4sUNWRpKoPC0pkog5kEUS8SEeTV5g_oU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});